version: '3'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  ui:
    image: nginx:1.23.4-alpine
    volumes:
      - ./ui/static:/usr/share/nginx/html
      - ./ui/dev-nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "4200:80"
