version: '3'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  ui:
    image: nginx:1.23.4-alpine
    volumes:
      - ./ui/static:/usr/share/nginx/html
      - ./ui/dev-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq