version: '3'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
  
  ui:
    image: yustheyokai/swkom-ws23-ui:latest
    ports:
      - "4200:80"
