version: '3'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ui:
    image: nginx:1.23.4-alpine
    volumes:
      - ./ui/static:/usr/share/nginx/html
      - ./ui/dev-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  # minio:
  #   image: quay.io/minio/minio
  #   entrypoint: "server /data --console-address :9090"
  #   ports:
  #     - "9000:9000"
  #     - "9090:9090"
  #   volumes:
  #     - ${HOME}/minio/data:/data
  #   environment:
  #     MINIO_ROOT_USER: minio
  #     MINIO_ROOT_PASSWORD: minio

  elastic_search:
    image: elasticsearch:8.7.1
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"
    # ulimits:
    #   memlock:
    #     soft: -1
    #     hard: -1
    ports:
      - 9200:9200
      - 9300:9300
  kibanba:
    image: docker.elastic.co/kibana/kibana:8.2.3
    ports:
      - 5601:5601

