version: '3'
services:
  db:
    image: postgres:16.0
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"

  ui:
    image: nginx:1.23.4-alpine
    volumes:
      - ./ui/static:/usr/share/nginx/html
      - ./ui/dev-nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "4200:80"

  rabbitmq:
    image: rabbitmq:3.12.8-management
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: rabbitmq
      RABBITMQ_DEFAULT_PASS: rabbitmq

  elastic_search:
    image: elasticsearch:8.11.3
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "xpack.security.enabled=false"
      - "xpack.security.enrollment.enabled=false"

    
    ports:
      - 9200:9200
      - 9300:9300
   
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9090:9090"
    volumes:
      - ${HOME}/minio/data:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
    command: server /data --console-address :9090
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/minio/login"]
      interval: 30s
      timeout: 20s
      retries: 3

  minio-s3-bucket:
    image: minio/mc:latest
    depends_on:
      minio:
        condition: service_healthy
    entrypoint: >
      /bin/sh -c "
      /usr/bin/mc alias set minio http://minio:9000 minio minio123 &&
      /usr/bin/mc mb minio/paperless"

